<div id="left_panel">
<a href="../index.php">Home</a>
<br />
<br />
	<span class="bold">Lab Assignments:</span>
		<ul id="sitemap">
			<li><a href="laba1.php">Assignment 1</a> </li>
			<li><a href="../LabAssignment2/officeform.php">Assignment 2</a> </li>
			<li><a href="../LabAssignment3/laba3.php">Assignment 3</a> </li>
			<li><a href="../LabAssignment4/laba4.php">Assignment 4</a> </li>
		</ul>

	<span class="bold">Lab Practica:</span>
		<ul id="sitemap">
			<li><a href="../LabPracticum1/index.html">Practicum 1</a></li>
			<li><a href="../LabPracticum1/part1.html">Practicum 1<br />Sequel</a></li>
			<li><a href="../LabPracticum2/labp2.php"> Practicum 2</a></li>
		</ul>
	</p>
</div>
